const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom'),esbuild=require('esbuild');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'templates/account-settings.html'),'utf8').replace('<!-- account-id -->','user-a');
const bundle=esbuild.buildSync({entryPoints:[path.join(root,'static/auth/account-settings.js')],bundle:true,write:false,format:'iife'}).outputFiles[0].text;
const dom=new JSDOM(html,{url:'http://localhost/account',runScripts:'outside-only'}),w=dom.window;
w.structuredClone=structuredClone;
const calls=[];let fail=false;
w.fetch=async(url,options)=>{calls.push({url,options});return {ok:!fail,status:fail?400:200,json:async()=>fail?{detail:'Current password is incorrect.'}:url==='/auth/me'?{name:'Daksh',email:'test@example.com'}:{name:'New name',message:'Display name updated.'}};};
w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};
w.HTMLDialogElement.prototype.close=function(){this.open=false;};
const $=id=>w.document.getElementById(id),tick=()=>new Promise(r=>setTimeout(r,10));
const waitFor=async predicate=>{for(let i=0;i<100;i++){if(predicate())return;await tick();}throw Error('Timed out waiting for account settings hydration.');};
const submit=id=>$(id).dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));
(async()=>{
  w.eval(bundle);await waitFor(()=>$('display-name').value==='Daksh');assert.equal($('verified').hidden,false);
  $('display-name').value='New name';submit('profile-form');await tick();assert.equal($('profile-name').textContent,'New name');
  const request=calls.find(c=>c.url==='/api/account/profile');assert.equal(request.options.headers['X-HyperSense-Account'],'user-a');
  $('new-password').value='long-password-123';$('confirm-password').value='different-password';submit('password-form');await tick();
  assert($('settings-status').textContent.includes('do not match'));assert(!calls.some(c=>c.url==='/api/account/password'));
  $('open-delete').click();assert($('delete-dialog').open);$('cancel-delete').click();assert(!$('delete-dialog').open);
  $('open-delete').click();$('delete-password').value='wrong-password';$('delete-confirmation').value='DELETE';fail=true;submit('delete-form');await tick();
  assert($('delete-dialog').open);assert($('delete-status').textContent.includes('incorrect'));assert.equal($('cancel-delete').disabled,false);
  assert.equal(JSON.parse(calls.find(c=>c.url==='/api/account').options.body).current_password,'wrong-password');
  $('cancel-delete').click();fail=false;
  $('current-password').value='current-password-123';$('new-password').value='new-password-12345';$('confirm-password').value='new-password-12345';
  submit('password-form');await tick();
  const passwordRequest=calls.find(c=>c.url==='/api/account/password');
  assert.deepEqual(JSON.parse(passwordRequest.options.body),{current_password:'current-password-123',password:'new-password-12345'});
  for(const id of ['current-password','new-password','confirm-password'])assert.equal($(id).value,'');
  assert($('password-form').querySelector('fieldset').disabled);
  console.log('PASS: account settings profile save, account header, password mismatch, deletion cancellation and error recovery.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>w.close());
