const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {JSDOM}=require('jsdom'),esbuild=require('esbuild');
const root=path.resolve(__dirname,'..');
let shell=fs.readFileSync(path.join(root,'templates/index.html'),'utf8');
for(const name of ['setup','interview','dashboard','camera-check','results'])shell=shell.replace('<!-- include:'+name+' -->',fs.readFileSync(path.join(root,'templates/screens',name+'.html'),'utf8'));
shell=shell.replace(/<script type="module"[\s\S]*?<\/script>/,'');
const code=esbuild.buildSync({stdin:{contents:`import {initMobileShell} from './mobile-shell.js';import {initSetup} from './setup.js';Object.assign(window,{initMobileShell,initSetup});`,resolveDir:path.join(root,'static/js')},bundle:true,write:false,format:'iife'}).outputFiles[0].text;
const dom=new JSDOM(shell,{url:'https://app.test/interview',runScripts:'outside-only'}),w=dom.window;
let phone=true;const listeners=[];
w.matchMedia=query=>({get matches(){return phone;},addEventListener(event,fn){listeners.push(fn);}});
w.eval(code);w.initSetup();
const source=w.document.getElementById('session-source');
let changes=0;source.addEventListener('change',()=>changes++);
const originalSummary=w.document.querySelector('#session-setup > details.setup-disclosure summary').innerHTML;
w.initMobileShell();
assert.equal(w.document.getElementById('session-title').textContent,'Your next interview');
assert(w.document.getElementById('account-menu').contains(w.document.getElementById('account-import')));
assert(w.document.getElementById('mobile-session-options').contains(w.document.getElementById('auto-flow')));
assert(!w.document.getElementById('mobile-session-options').contains(source),'Question source remains an essential setting');
w.document.getElementById('technology').value='SQL';source.value='gemini';source.dispatchEvent(new w.Event('change'));
assert.equal(w.document.getElementById('manual-question-fields').hidden,true);
phone=false;listeners.forEach(fn=>fn());
assert.equal(w.document.getElementById('mobile-session-options'),null);
assert(w.document.querySelector('.account-tools').contains(w.document.getElementById('account-import')));
assert.equal(w.document.querySelector('#session-setup > details.setup-disclosure summary').innerHTML,originalSummary);
assert.equal(w.document.getElementById('technology').value,'SQL');
assert.equal(source.value,'gemini');
phone=true;listeners.forEach(fn=>fn());
assert.equal(w.document.querySelectorAll('#mobile-session-options').length,1);
assert.equal(w.document.querySelectorAll('#session-source').length,1);
source.value='manual';source.dispatchEvent(new w.Event('change'));
assert.equal(w.document.getElementById('manual-question-fields').hidden,false);
assert.equal(changes,2,'The original source handler survives both rearrangements');
w.document.getElementById('account-menu').hidden=false;w.document.getElementById('mobile-account-toggle').click();
assert.equal(w.document.getElementById('mobile-account-toggle').getAttribute('aria-expanded'),'true');
w.document.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape'}));
assert.equal(w.document.getElementById('mobile-account-toggle').getAttribute('aria-expanded'),'false');
dom.window.close();console.log('PASS: mobile setup restructuring, essential source controls, desktop restoration, retained values/listeners and account menu dismissal.');
