// Full-page integration test: npm ci, then npm test.
// All camera, audio and provider responses are simulated. No API keys needed.
const fs=require('node:fs');
const path=require('node:path');
const assert=require('node:assert/strict');
const {JSDOM,VirtualConsole}=require('jsdom');
const {indexedDB,IDBKeyRange}=require('fake-indexeddb');
const esbuild=require('esbuild');
const root=path.resolve(__dirname,'..');
let shell=fs.readFileSync(path.join(root,'templates/index.html'),'utf8');
for(const name of ['setup','interview','dashboard','camera-check','results'])shell=shell.replace('<!-- include:'+name+' -->',fs.readFileSync(path.join(root,'templates/screens',name+'.html'),'utf8'));
const modules=fs.readdirSync(path.join(root,'static/js')).filter(n=>n.endsWith('.js')&&n!=='app.js');
const entry=`import './app.js';\n`+modules.map((n,i)=>`import * as m${i} from './${n}';`).join('\n')+modules.map((n,i)=>`Object.assign(window,m${i});`).join('\n')+`\nfor(const key of Object.keys(window.state))Object.defineProperty(window,key,{configurable:true,get:()=>window.state[key],set:value=>{window.state[key]=value}});`;
const bundle=esbuild.buildSync({stdin:{contents:entry,resolveDir:path.join(root,'static/js')},bundle:true,write:false,format:'iife'}).outputFiles[0].text;
shell=shell.replace(/<script type="module"[\s\S]*?<\/script>/,'');
const errors=[];
const virtualConsole=new VirtualConsole();
virtualConsole.on('jsdomError',e=>errors.push(e.message));
let denyEvaluation=false;
function createBrowser(){ return new JSDOM(shell,{
    url:'http://localhost:8000/interview',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole,
    beforeParse(w){
        w.indexedDB=indexedDB;w.IDBKeyRange=IDBKeyRange;w.structuredClone=structuredClone;
        w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=()=>{};
        w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.load=()=>{};w.HTMLMediaElement.prototype.play=async()=>{};
        w.HTMLCanvasElement.prototype.getContext=()=>({clearRect(){},strokeRect(){},drawImage(){}});
        w.URL.createObjectURL=()=> 'blob:test';w.URL.revokeObjectURL=()=>{};w.confirm=()=>true;
        w.fetch=async(url)=>({ok:!denyEvaluation,status:denyEvaluation?429:200,text:async()=>JSON.stringify(denyEvaluation?{detail:'Quota reached'}:{score:0,feedback:'Missing the required explanation.',provider:'Test',model:'mock',coaching:[]})});
    }
}); }
const dom=createBrowser();
dom.window.eval(bundle);
const w=dom.window,$=id=>w.document.getElementById(id),evaluate=code=>w.eval(code);
const waitFor=async fn=>{for(let i=0;i<100;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('UI condition timed out');};
(async()=>{
    await waitFor(()=>$('saved-session-list').textContent.includes('No completed'));
    assert.equal($('nav-practice').getAttribute('aria-current'),'page');
    $('session-questions').value='Keep my questions';$('session-source').value='gemini';$('session-source').dispatchEvent(new w.Event('change'));
    assert.equal($('manual-question-fields').hidden,true);
    $('session-source').value='manual';$('session-source').dispatchEvent(new w.Event('change'));
    assert.equal($('manual-question-fields').hidden,false);assert.equal($('session-questions').value,'Keep my questions');
    await $('camera-on').onclick();assert.equal(evaluate('state.cameraStream'),null);
    evaluate(`cameraStream={getVideoTracks:()=>[{readyState:'live',enabled:true}],getTracks:()=>[{stop(){}}]};`);
    evaluate('updatePose([[1,0,0],[0,1,0],[0,0,1]],2)');assert.equal(evaluate('state.neutralRotation'),null);
    for(let i=0;i<5;i++)evaluate('updatePose([[1,0,0],[0,1,0],[0,0,1]],1)');
    assert.equal(evaluate('cameraReady()'),true);evaluate('stopCamera()');
    evaluate('renderQuestion("Example: `items`\\n\\n```python\\nif items:\\n    print(items)\\n```\\n\\n<script>bad()</script>")');
    assert.equal($('question').querySelector('pre code').textContent,'if items:\n    print(items)');assert.equal($('question').querySelector('script'),null);
    $('nav-dashboard').click();await waitFor(()=>$('dashboard-status').textContent.includes('first saved'));
    assert.equal($('dashboard-page').hidden,false);
    await evaluate(`sessionStore('readwrite',s=>s.put({id:'seed',date:'2026-01-01T12:00:00Z',settings:{technology:'Python',difficulty:'easy',interview_type:'mixed'},total:2,answers:[{score:0,interview_type:'technical',answer:'A',question:'Q',feedback:'Test',audio:{words_per_minute:120},confidence:'2'},{score:null,interview_type:'hr',question:'HR',answer:'B'}]}))`);
    await evaluate('renderDashboard()');assert($('dashboard-types').textContent.includes('0.0/100'));
    $('dashboard-filter').value='hr';$('dashboard-filter').onchange();await waitFor(()=>$('dashboard-status').textContent.startsWith('Updated'));
    assert($('dashboard-stats').textContent.includes('Pending scores1'));
    await evaluate('openSavedSession("seed")');assert.equal($('results-page').hidden,false);
    assert($('session-report').textContent.includes('Not scored'));
    assert.equal($('export-report').disabled,false);
    $('nav-dashboard').click();await waitFor(()=>$('dashboard-status').textContent.startsWith('Updated'));
    $('dashboard-start').click();assert.equal($('dashboard-page').hidden,true);
    assert.equal($('session-setup').style.display,'block');
    // A one-question manual session with a simulated calibrated camera.
    evaluate(`cameraStream={getVideoTracks:()=>[{readyState:'live',enabled:true}],getTracks:()=>[{stop(){window.cameraStopped=true;}}]};neutralRotation=[[1,0,0],[0,1,0],[0,0,1]];`);
    $('session-count').appendChild(new w.Option('1','1'));$('session-count').value='1';$('session-source').value='manual';$('session-questions').value='Explain a Python list.';$('auto-flow').value='manual';
    evaluate('showInterviewPage()');await evaluate('startCheckedSession()');evaluate('refresh()');
    assert.equal($('session-controls').hidden,false);assert.equal($('nav-dashboard').disabled,true);
    $('transcript').value='A list stores items.';$('confidence-rating').value='4';evaluate('refresh()');
    denyEvaluation=true;await evaluate('run(submitAnswer)');assert.equal($('transcript').value,'A list stores items.');assert.equal($('transcript').disabled,false);
    assert.equal(evaluate('interviewSession.answers.length'),0);
    // Browser Back must keep the active interview visible.
    w.history.pushState({},'','/results?session=seed');await evaluate('restorePageRoute()');assert.equal($('interview-workspace').style.display,'block');
    // Continue without quota; completion releases camera and preserves rating.
    await $('session-next').onclick();await waitFor(()=>$('session-storage-status').textContent==='Session and recordings saved in this browser.');
    assert.equal(w.cameraStopped,true);assert.equal($('results-page').hidden,false);assert.equal(evaluate('interviewSession.answers[0].confidence'),'4');
    assert.equal(evaluate('interviewSession.answers[0].score'),null);
    denyEvaluation=false;await evaluate('scorePendingAnswers()');assert.equal(evaluate('interviewSession.answers[0].score'),0);
    const id=evaluate('interviewSession.id');await evaluate(`openSavedSession(${JSON.stringify(id)})`);assert($('session-report').textContent.includes('0/100'));
    await evaluate(`deleteSavedSession(${JSON.stringify(id)})`);assert.equal(await evaluate(`sessionStore('readonly',s=>s.get(${JSON.stringify(id)}))`),undefined);
    // Early completion and a blocked navigation while the session is active.
    evaluate(`cameraStream={getVideoTracks:()=>[{readyState:'live',enabled:true}],getTracks:()=>[{stop(){window.cameraStopped=true;}}]};neutralRotation=[[1,0,0],[0,1,0],[0,0,1]];`);
    $('session-count').appendChild(new w.Option('2','2'));$('session-count').value='2';$('session-questions').value='First question\n---\nSecond question';
    evaluate('showInterviewPage()');await evaluate('startCheckedSession()');evaluate('refresh()');$('transcript').value='Early answer';
    evaluate('showDashboard()');assert.equal($('dashboard-page').hidden,true);
    $('session-end').click();await waitFor(()=>$('session-storage-status').textContent==='Session and recordings saved in this browser.');
    assert.equal(evaluate('interviewSession.answers.length'),1);assert.equal(evaluate('interviewSession.total'),2);assert.equal(evaluate('cameraStream'),null);
    $('nav-practice').click();$('manual-question').value='Single question';
    $('camera-consent').checked=false;$('use-manual').click();assert.equal(w.state.current,null);
    assert($('single-practice-status').textContent.includes('consent'));
    $('single-camera-consent').checked=true;$('single-camera-consent').dispatchEvent(new w.Event('change'));assert.equal($('camera-consent').checked,true);
    const originalCameraOn=$('camera-on').onclick;$('camera-on').onclick=()=>{};
    $('use-manual').click();assert.equal($('camera-check-page').hidden,false);assert.equal(w.state.current.question,'Single question');assert.equal(w.state.ticker,null);
    w.state.cameraStream={getVideoTracks:()=>[{readyState:'live',enabled:true}],getTracks:()=>[{stop(){}}]};w.state.neutralRotation=[[1,0,0],[0,1,0],[0,0,1]];
    await $('camera-check-continue').onclick();assert.equal($('interview-workspace').style.display,'block');assert.equal(w.state.current.question,'Single question');assert.equal(w.state.interviewSession?.active,false);
    $('transcript').value='Preserve my answer';w.state.deadline=Date.now()+25000;
    w.showCameraCheck(false);assert.equal(w.state.ticker,null);const remaining=w.state.singleRemaining;
    $('camera-check-back').click();assert.equal($('interview-workspace').style.display,'block');assert.equal($('transcript').value,'Preserve my answer');assert.equal(w.state.current.question,'Single question');assert(w.state.deadline-Date.now()<=remaining);
    $('camera-on').onclick=originalCameraOn;w.state.singlePractice=false;w.stopCamera();clearInterval(w.state.ticker);w.state.ticker=null;

    const assessmentHost=w.document.createElement('div');
    const assessed={score:50,answer:'Lists are mutable.',assessment:{strengths:[{evidence:'Lists are mutable.',explanation:'Correct.'},{evidence:'invented quote',explanation:'Must not render'}],gaps:['Explain tuple mutability.'],next_step:'Compare both in one sentence.'}};
    w.renderAnswerAssessment(assessmentHost,assessed);
    assert(assessmentHost.textContent.includes('Explain tuple mutability.'));
    assert(!assessmentHost.textContent.includes('Must not render'));
    assert(assessmentHost.textContent.includes('Compare both in one sentence.'));
    const legacyHost=w.document.createElement('div');w.renderAnswerAssessment(legacyHost,{score:0});assert(legacyHost.textContent.includes('summary feedback only'));
    const pendingHost=w.document.createElement('div');w.renderAnswerAssessment(pendingHost,{score:null});assert.equal(pendingHost.textContent,'');
    const fullHost=w.document.createElement('div');w.renderAnswerAssessment(fullHost,{score:100,answer:'Correct',assessment:{strengths:[],gaps:[],next_step:'Try another question.'}});assert(fullHost.textContent.includes('Optional next practice'));
    const exported=w.exportSessionReport({settings:{},answers:[assessed]});assert.deepEqual(exported.answers[0].assessment,assessed.assessment);
    // Audio-derived answers require confirmation, including unscored archival.
    w.state.interviewSession=null;w.state.current={question:'Review test',auto_flow:true};
    w.state.speechPending=false;w.state.busy=false;w.state.answerSubmitted=false;
    w.setAudio(new w.Blob(['audio'],{type:'audio/webm'}),'review.webm');
    $('transcript').value='A list is mutable.';$('transcript').dispatchEvent(new w.Event('input'));
    assert.equal($('evaluate').disabled,true);
    await assert.rejects(()=>w.submitAnswer(),/confirm/);
    $('transcript-confirm').checked=true;$('transcript-confirm').dispatchEvent(new w.Event('change'));
    assert.equal(w.transcriptApproved(),true);assert.equal($('evaluate').disabled,false);
    $('transcript').value='A tuple is immutable.';$('transcript').dispatchEvent(new w.Event('input'));
    assert.equal(w.transcriptApproved(),false);
    w.state.interviewSession={active:true,loaded:true,answers:[]};
    await assert.rejects(()=>w.archiveSessionAnswer(),/confirm/);assert.equal(w.state.interviewSession.answers.length,0);
    w.state.interviewSession=null;
    const originalFetch=w.fetch;let evaluationRequests=0;
    w.fetch=async url=>{if(url==='/evaluate-answer')evaluationRequests++;return {ok:true,status:200,text:async()=>JSON.stringify({text:'Recognized answer',delivery:null})};};
    w.cancelAutomation();w.state.automationPaused=false;
    await w.autoProcessRecording();
    assert.equal($('transcript').value,'Recognized answer');assert.equal(evaluationRequests,0);
    assert.equal(w.state.automationTimer,null);assert.equal($('transcript-confirm').checked,false);
    assert($('automation-status').textContent.includes('Review, confirm'));
    w.fetch=originalFetch;w.clearAudio();
    assert.equal(w.transcriptApproved(),true); // Typed answers require no audio confirmation.
    console.log('PASS: review gate, edit invalidation, unscored submission gate and automatic transcription without submission.');
    // Refresh into a new window sharing only IndexedDB, including stored audio.
    await evaluate(`draftStore('readwrite',s=>s.clear())`);
    w.state.interviewSession={id:'recovery-test',date:new Date().toISOString(),active:true,loaded:true,total:2,source:'manual',questions:['First','Second'],settings:{technology:'Python',difficulty:'easy',language:'English',interview_type:'technical',auto_flow:false,resume_text:'private resume'},answers:[{question:'First',answer:'Saved answer',score:100,recording:{blob:new Blob(['audio bytes'],{type:'audio/webm'}),name:'answer-01.webm',bytes:11,url:'blob:expired'}}]};
    w.state.current={...w.state.interviewSession.settings,question:'Second'};
    await w.checkpointSession();
    const draft=await w.draftStore('readonly',s=>s.get('active'));
    assert.equal(draft.settings.resume_text,undefined);assert.equal(draft.pendingQuestion.resume_text,undefined);
    assert.equal(draft.answers[0].recording.url,undefined);
    const reloaded=createBrowser(),rw=reloaded.window;
    rw.eval(bundle);
    await waitFor(()=>!rw.document.getElementById('session-recovery').hidden);
    await assert.rejects(()=>rw.resumeSessionDraft(),/consent/);
    rw.document.getElementById('recovery-consent').checked=true;
    rw.document.getElementById('camera-on').onclick=()=>{};
    await rw.resumeSessionDraft();
    assert.equal(rw.state.interviewSession.answers[0].answer,'Saved answer');
    assert.equal(await rw.state.interviewSession.answers[0].recording.blob.text(),'audio bytes');
    assert.equal(rw.state.neutralRotation,null);
    rw.state.cameraStream={getVideoTracks:()=>[{readyState:'live',enabled:true}],getTracks:()=>[{stop(){}}]};
    rw.state.neutralRotation=[[1,0,0],[0,1,0],[0,0,1]];
    await rw.loadSessionQuestion();
    assert.equal(rw.state.current.question,'Second');assert.equal(rw.state.interviewSession.answers.length,1);
    const workingDB=rw.indexedDB;rw.indexedDB={open(){throw Error('Storage unavailable')}};
    await assert.rejects(()=>rw.checkpointSession(),/Could not save progress/);
    assert.equal(rw.state.interviewSession.answers[0].answer,'Saved answer');rw.indexedDB=workingDB;
    await rw.clearSessionDraft('different-session');assert(await rw.draftStore('readonly',s=>s.get('active')));
    await rw.clearSessionDraft('recovery-test');assert.equal(await rw.draftStore('readonly',s=>s.get('active')),undefined);
    reloaded.window.close();
    console.log('PASS: refresh recovery, audio persistence, consent gate, question continuation, résumé exclusion and storage failures.');
    // Retry preserves the original recording and compares a separately saved answer.
    const retryBrowser=createBrowser(),tw=retryBrowser.window;
    tw.eval(bundle);
    await waitFor(()=>tw.document.getElementById('saved-session-list').textContent.length>0);
    tw.document.getElementById('camera-on').onclick=()=>{};
    const original={id:'retry-original',date:new Date().toISOString(),total:1,active:false,settings:{technology:'Python',difficulty:'easy',language:'English',interview_type:'technical',auto_flow:false},answers:[{question:'Explain lists.',answer:'Original answer',score:40,feedback:'Explain mutability.',recording:{blob:new Blob(['original audio']),name:'original.webm',bytes:14}}]};
    tw.state.interviewSession=original;
    await tw.retryQuestion(original,0);
    assert.equal(tw.state.current.question,'Explain lists.');
    assert.equal(tw.document.getElementById('camera-check-page').hidden,false);
    assert.equal(tw.document.getElementById('transcript').value,'');
    assert.equal(tw.state.retryContext.score,40);
    tw.state.cameraStream={getVideoTracks:()=>[{readyState:'live',enabled:true}],getTracks:()=>[{stop(){}}]};
    tw.state.neutralRotation=[[1,0,0],[0,1,0],[0,0,1]];
    tw.state.deadline=Date.now()+60000;
    tw.document.getElementById('transcript').value='Lists are mutable.';
    tw.fetch=async()=>({ok:true,status:200,text:async()=>JSON.stringify({score:90,feedback:'Correct explanation.'})});
    await tw.submitAnswer();
    await waitFor(()=>tw.state.sessionSavePending===null);
    assert.notEqual(tw.state.interviewSession.id,original.id);
    assert(tw.document.getElementById('session-report').textContent.includes('Change: +50 points'));
    const kept=await tw.sessionStore('readonly',s=>s.get('retry-original'));
    assert.equal(kept.answers[0].answer,'Original answer');
    assert.equal(await kept.answers[0].recording.blob.text(),'original audio');
    const retried=await tw.sessionStore('readonly',s=>s.get(tw.state.interviewSession.id));
    assert.equal(retried.answers[0].retryOf.sessionId,'retry-original');
    await tw.openSavedSession(retried.id);
    assert(tw.document.getElementById('session-report').textContent.includes('Change: +50 points'));
    tw.showSetupPage();assert.equal(tw.state.retryContext,null);
    const retryDB=tw.indexedDB;tw.indexedDB={open(){throw Error('Unavailable')}};
    await assert.rejects(()=>tw.retryQuestion(original,0),/Save the original/);
    assert.equal(tw.state.current,null);tw.indexedDB=retryDB;
    retryBrowser.window.close();
    console.log('PASS: retry camera gate, separate saved attempt, score comparison after reload, original audio preservation and storage failure gate.');
    assert.deepEqual(errors,[]);
    console.log('PASS: empty dashboard, filters, zero/pending scores, reports, quota recovery, session navigation, completion, camera cleanup, confidence persistence, retry scoring, deletion and single practice.');
})().catch(e=>{console.error(e);process.exitCode=1;}).finally(()=>w.close());
