"""Private PostgreSQL storage. Parameterized queries and bounded transactions."""
from contextlib import contextmanager
import os
import re
import sqlite3
from threading import Lock
from backend.accounts.schema import SQLITE_SCHEMA

SCHEMA = 'hypersense'
LOCK_ID = 842901604
_ready = set()
_guard = Lock()
TABLES = ('users','logins','links','attempts','account_suspensions','admin_audit',
          'support_reports','support_receipts','support_messages','support_threads',
          'support_admin_reads','interviews','counters')
COUNTERS = '''CREATE TABLE IF NOT EXISTS counters (
 hour BIGINT NOT NULL, kind TEXT NOT NULL, operation TEXT NOT NULL,
 provider TEXT NOT NULL, outcome TEXT NOT NULL, fallback BIGINT NOT NULL,
 count BIGINT NOT NULL, total_ms DOUBLE PRECISION NOT NULL,
 PRIMARY KEY(hour,kind,operation,provider,outcome,fallback))'''


class Row:
    """Match sqlite.Row's named/indexed access and value iteration."""
    def __init__(self, names, values): self.names=names;self.values=values
    def keys(self): return self.names
    def __getitem__(self,key): return self.values[key if isinstance(key,(int,slice)) else self.names.index(key)]
    def __iter__(self): return iter(self.values)
    def __len__(self): return len(self.values)


class Cursor:
    def __init__(self,cursor): self.cursor=cursor
    def convert(self,row):
        return None if row is None else Row([c.name for c in self.cursor.description],row)
    def fetchone(self): return self.convert(self.cursor.fetchone())
    def fetchall(self): return [self.convert(row) for row in self.cursor.fetchall()]
    def __iter__(self): return (self.convert(row) for row in self.cursor)


def bind_sql(query):
    # Preserve question marks in SQL literals/identifiers. Data stays in parameters.
    query=query.replace('%','%%')
    return re.sub(r"'(?:''|[^'])*'|\"(?:\"\"|[^\"])*\"|\?",lambda m:'%s' if m.group()=='?' else m.group(),query)


class Connection:
    def __init__(self,raw): self.raw=raw
    def execute(self,query,params=()):
        if query.strip().upper() in ('BEGIN','BEGIN IMMEDIATE'):
            # The outer context already owns a transaction and the write lock.
            return Cursor(self.raw.execute('SELECT 1'))
        return Cursor(self.raw.execute(bind_sql(query) if params else query,params if params else None))


def schema_statements():
    for statement in SQLITE_SCHEMA.split(';'):
        statement=statement.strip()
        if not statement: continue
        if statement.startswith('INSERT OR IGNORE'): continue
        statement=statement.replace('INTEGER PRIMARY KEY AUTOINCREMENT','BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        statement=re.sub(r'\bINTEGER\b','BIGINT',statement)
        yield statement
    yield COUNTERS


def raw_connect(url=None):
    import psycopg
    from psycopg.conninfo import conninfo_to_dict
    value=(url or os.getenv('DATABASE_URL','')).strip()
    if not value.startswith(('postgresql://','postgres://')):
        raise ValueError('DATABASE_URL must be a PostgreSQL connection URL.')
    options=conninfo_to_dict(value)
    options['connect_timeout']='10'
    # Encrypt remote connections by default. Local test servers can explicitly opt out.
    options.setdefault('sslmode','require')
    return psycopg.connect(**options,autocommit=True,prepare_threshold=None)


def initialize(raw,key):
    with _guard:
        if key in _ready: return
        with raw.transaction():
            raw.execute("SET LOCAL statement_timeout='30s'")
            raw.execute("SET LOCAL lock_timeout='10s'")
            raw.execute('SELECT pg_advisory_xact_lock(%s)',(LOCK_ID,))
            raw.execute('CREATE SCHEMA IF NOT EXISTS hypersense')
            raw.execute('REVOKE ALL ON SCHEMA hypersense FROM PUBLIC')
            raw.execute('SET LOCAL search_path TO hypersense,pg_catalog')
            for statement in schema_statements(): raw.execute(statement)
            # Tables never belong to Supabase's exposed public schema.
            raw.execute('REVOKE ALL ON ALL TABLES IN SCHEMA hypersense FROM PUBLIC')
            for table in TABLES:
                raw.execute('ALTER TABLE hypersense.'+table+' ENABLE ROW LEVEL SECURITY')
        _ready.add(key)


@contextmanager
def connection():
    raw=None
    try:
        import psycopg
    except ImportError:
        raise sqlite3.OperationalError('PostgreSQL driver missing. Install requirements-postgres.txt.') from None
    try:
        key=os.getenv('DATABASE_URL','').strip()
        raw=raw_connect(key);initialize(raw,key)
        with raw.transaction():
            raw.execute("SET LOCAL statement_timeout='30s'")
            raw.execute("SET LOCAL lock_timeout='10s'")
            raw.execute('SELECT pg_advisory_xact_lock(%s)',(LOCK_ID,))
            raw.execute('SET LOCAL search_path TO hypersense,pg_catalog')
            yield Connection(raw)
    except psycopg.IntegrityError:
        raise sqlite3.IntegrityError('Database constraint violation.') from None
    except (psycopg.Error, ValueError):
        # Do not leak connection strings, SQL parameters or account data in logs.
        raise sqlite3.OperationalError('PostgreSQL operation failed. Check connection, permissions and availability.') from None
    finally:
        if raw is not None: raw.close()
